apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  labels:
    env: local
spec:
  source:
    directory:
      include: '**/0-local/*.yaml'
  destination:
    server: https://kubernetes.default.svc

