apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-local-whoami
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/niehaitao/lil-whoami.git
    targetRevision: HEAD
    path: helm
    helm:
      values: |
        ingress:
          host: localhost
          path: /who-am-i
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
